name: ansi
description: Ansi utilities package to handle string with ansi characters.
version: 0.0.1
homepage: https://github.com/hyiso/ansi

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
