name: ansi_monorepo
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  commitlint_cli: ^0.8.0
  husky: ^0.1.6
  lint_staged: ^0.5.0
  melos: ^3.0.0

lint_staged:
  '**/*.dart': dart format --fix  && dart fix --apply