name: ansi_wrap
description: Wordwrap a string with ANSI escape codes.
version: 0.1.0
homepage: https://github.com/hyiso/ansi
repository: https://github.com/hyiso/ansi/tree/main/packages/ansi_wrap

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansi_codes: ^0.1.0
  ansi_strip: ^0.1.0
  characters: ^1.2.1
  string_width: ^0.1.2

dev_dependencies:
  ansi: ^0.2.0
  ansi_regex: ^0.1.0
  lints: ^2.0.0
  test: ^1.16.0
