name: ansi_wrap
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ansi_codes: ^0.1.0
  ansi_strip: ^0.1.0
  characters: ^1.2.1
  string_width: ^0.1.0

dev_dependencies:
  ansi: ^0.2.0
  ansi_regex: ^0.1.0
  lints: ^2.0.0
  test: ^1.16.0
