name: ansi_regex
description: Regular expression for matching ANSI escape codes.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
