name: ansi_codes
description: ANSI escape codes for styling strings in the terminal.
version: 0.1.0
homepage: https://github.com/hyiso/ansi
repository: https://github.com/hyiso/ansi/tree/main/packages/ansi_codes

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
